# viewing list of users
GET http://localhost:3000/users
###


# creating and registering a user
POST http://localhost:3000/users
Content-Type: application/json

{
    "userid": "arjunob96",
    "password": "test-password"
}

###
# Login
POST http://localhost:3000/login
Content-Type: application/json

{
    "userid": "arjunob96",
    "password": "test-password"
}

###
# View Meetings
GET http://localhost:3000/meetings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYXJqdW5vYjk2IiwiaWF0IjoxNjQxNzM1MTI2fQ.XK3Skwfl2NlG8V8KoZioytMi7MOhWzsmPmA7Cwg1wnc

###
# Create Meetings
POST http://localhost:3000/meetings 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYXJqdW5vYjk2IiwiaWF0IjoxNjQxNzM1MTI2fQ.XK3Skwfl2NlG8V8KoZioytMi7MOhWzsmPmA7Cwg1wnc

{
    "date_of_meeting": "2022-01-11",
        "start_time": "13:00",
        "end_time": "13:30",
        "description": "Another test meeting",
        "email_attendees": "abc@gmail.com, xyz@gmail.com"
}

###
GET http://localhost:3000/meetings/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYXJqdW5vYjk2IiwiaWF0IjoxNjQxNzM1MTI2fQ.XK3Skwfl2NlG8V8KoZioytMi7MOhWzsmPmA7Cwg1wnc
